defaults:
  - encoder: clip_frozen
  - kge: kge_ri
  - optimizer: adamw
  - lr_scheduler: cosine_annealing
_target_: knowcol.models.knowcol.KnowCoL
beta1: 1.0
beta2: 1.0
temperature: 0.07
margin: 1.0
_recursive_: false