defaults:
  - encoder: clip_fusion
  - kge: kge_ri
  - optimizer: adam
  - lr_scheduler: cosine_annealing
_target_: knowcol.models.knowcol_transE.KnowCoL
beta1: 0.1
beta2: 0.1
temperature: 0.07
_recursive_: false