defaults:
  - train_dataset_cfg: entity_query
  - val_dataset_cfg: entity_query
  - test_entity_dataset_cfg: default
  - test_query_dataset_cfg: default
_target_: knowcol.datasets.data_module.DataModule
_recursive_: false
num_workers: 8
batch_size: 512
tokenizer: ${model.encoder.model}
n_px: 224
shuffle_val: False