defaults:
  - train_dataset_cfg: entity
  - val_dataset_cfg: entity
_target_: knowcol.datasets.data_module.DataModule
_recursive_: false
num_workers: 16
batch_size: 2048
tokenizer: ${model.encoder.model}
n_px: 224
shuffle_val: False